[package]
name = "pyvoy"
version = "0.1.3"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/curioswitch/pyvoy"

[dependencies]
envoy-proxy-dynamic-modules-rust-sdk = { git = "https://github.com/envoyproxy/envoy", tag = "v1.36.2" }

crossbeam-channel = "0.5.15"
encoding_rs = "0.8.35"
http = "1.4.0"
itoa = "1.0.15"
pyo3 = "0.27.2"
urlencoding = "2.1.3"
yaml-rust2 = "0.10.4"

[build-dependencies]
pyo3-build-config = { version = "0.27.1", features = ["resolve-config"] }

[lib]
name = "pyvoy"
path = "src/lib.rs"
crate-type = ["cdylib"]
