[project]
site_name = "pyvoy"
site_url = "https://pyvoy.dev"
site_description = "A Python application server built with Envoy"
site_author = "CurioSwitch"
copyright = "&copy; CurioSwitch"
repo_url = "https://github.com/curioswitch/pyvoy"
edit_uri = "edit/main/docs/"
nav = [
    { "Introduction" = "index.md" },
    "settings.md",
    "deployment.md",
    "design.md",
]

[project.theme]
favicon = "img/favicon.png"
logo = "img/logo.png"
features = ["content.action.edit"]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
