[project]
site_name = "pyvoy"
site_url = "https://pyvoy.dev"
site_description = "A Python application server built with Envoy"
site_author = "CurioSwitch"
copyright = "&copy; CurioSwitch"
repo_url = "https://github.com/curioswitch/pyvoy"
edit_uri = "edit/main/docs/"

[project.theme]
favicon = "img/favicon.png"
logo = "img/logo.png"
features = ["content.action.edit"]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
