name: Benchmark
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.lock"
      - "bench/**"
      - ".github/workflows/bench.yaml"
  # Just verify the harness on PRs, no need for actual numbers
  pull_request:
    paths:
      - "bench/**"
      - ".github/workflows/bench.yaml"
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # It's overkill to run benchmarks on multiple Pythons like we do tests,
        # but we will need it eventually to compare with free-threaded Python.
        python:
          - "3.14"
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: tests/go/go.mod
          cache-dependency-path: vegeta

      - run: uv sync --python ${{ matrix.python }} --managed-python

      - run: uv run poe bench ${{ github.event_name == 'pull_request' && '--short' || '' }}
