name: Benchmark
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.lock"
      - "bench/**"
      - ".github/workflows/bench.yaml"
  # Just verify the harness on PRs, no need for actual numbers
  pull_request:
    paths:
      - "bench/**"
      - ".github/workflows/bench.yaml"
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # It's overkill to run benchmarks on multiple Pythons like we do tests,
        # but we will need it eventually to compare with free-threaded Python.
        python:
          - "3.14"
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: tests/go/go.mod
          cache-dependency-path: vegeta

      - run: uv sync --python ${{ matrix.python }} --managed-python

      - run: uv run poe bench ${{ github.event_name == 'pull_request' && '--short' || '' }}
