name: Benchmark
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.lock"
      - "bench/**"
      - ".github/workflows/bench.yaml"
  # Just verify the harness on PRs, no need for actual numbers
  pull_request:
    paths:
      - "bench/**"
      - ".github/workflows/bench.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # Overkill to benchmark with every Python version, we just use the latest.
        python:
          - "3.14"
          - "3.14t"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0

      - run: rustup update

      - run: cargo install --features http3 oha

      - run: uv sync --python ${{ matrix.python }} --managed-python

      - run: uv run poe bench ${{ github.event_name == 'pull_request' && '--short' || '' }}
