name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  attestations: write
  id-token: write

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
        python:
          - "3.10"
          - "3.14"
        # Test oldest and newest on all OS's, but others only on one
        # to save CI load.
        include:
          - os: ubuntu-24.04
            python: "3.11"
          - os: ubuntu-24.04
            python: "3.12"
          - os: ubuntu-24.04
            python: "3.13"
          # Enable coverage on just one job
          - os: ubuntu-24.04
            python: "3.14"
            coverage: "cov"

    env:
      # Avoid multiple compile e.g. in lint and test by setting as a job env var
      RUSTFLAGS: ${{ matrix.coverage == 'cov' && '-C instrument-coverage' || '' }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: tests/go/go.mod
          cache-dependency-path: "**/go.mod"

      - name: Setup rust
        run: |
          rustup update
          ${{ matrix.coverage == 'cov' && 'rustup component add llvm-tools' || '' }}

      - run: uv lock --check

      - run: uv sync --python ${{ matrix.python }} --managed-python

      # Go ahead and run lint on all Python versions since we may have version-specific
      # guards in rust in the future.
      - name: run lints
        if: startsWith(matrix.os, 'ubuntu-')
        run: uv run poe lint

      - name: run tests
        run: uv run poe test

      - name: prepare coverage
        if: ${{ matrix.coverage == 'cov' }}
        run: |
          $(rustc --print=target-libdir)/../bin/llvm-profdata merge -sparse default_*.profraw tests/go/default_*.profraw -o tests.profdata
          $(rustc --print=target-libdir)/../bin/llvm-cov export -format=lcov --ignore-filename-regex='/.cargo/registry' --ignore-filename-regex='.cargo/git/checkouts' --ignore-filename-regex='.rustup/toolchains' -instr-profile tests.profdata pyvoy/_bin/libpyvoy.so > tests.lcov

      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        if: ${{ matrix.coverage == 'cov' }}

  publish:
    runs-on: ubuntu-24.04
    environment: ${{ github.event_name != 'pull_request' && 'dev' || null }}
    needs: build
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: pyproject.toml

      - name: Setup rust
        run: rustup update

      - run: uv run poe wheel

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        if: github.event_name != 'pull_request'
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
