name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - zensical.toml
      - ".github/workflows/docs.yaml"
  pull_request:
    paths:
      - "docs/**"
      - zensical.toml
      - ".github/workflows/docs.yaml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: ${{ github.event_name != 'pull_request' && 'github-pages' || null }}
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1

      - run: uv run --group docs --no-dev zensical build --clean

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        if: github.event_name != 'pull_request'
        with:
          path: site

      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        if: github.event_name != 'pull_request'
        id: deployment
