name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - zensical.toml
      - ".github/workflows/docs.yaml"
  pull_request:
    paths:
      - "docs/**"
      - zensical.toml
      - ".github/workflows/docs.yaml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: ${{ github.event_name != 'pull_request' && 'github-pages' || null }}
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4

      - run: uv sync --python 3.14

      - run: uv run zensical build --clean

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        if: github.event_name != 'pull_request'
        with:
          path: site

      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        if: github.event_name != 'pull_request'
        id: deployment
