name: Renovate Dependencies

on:
  schedule:
    # https://crontab.guru/#5_12_*_*_1
    - cron: "5 12 * * 1"
  workflow_dispatch:

# Uses app token so default token needs no permissions
permissions: {}

jobs:
  renovate:
    uses: curioswitch/go-build/.github/workflows/export-renovate.yaml@8304121f488a5faa0b1ff094b6e2abc8da5b6c43 # v0.7.1
    with:
      github_app_id: "1047503"
    secrets:
      github_app_key: ${{ secrets.CURIOSWITCH_APP_KEY }}
